name: Publish to Nuget

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x
      - name: Pack
        run: dotnet pack src/Meilisearch/Meilisearch.csproj -c Release -o src/Meilisearch/bin/Release
      - name: Publish
        run: dotnet nuget push src/Meilisearch/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
